// PLAN-SANDBOX SBX1: pure sandbox builders (naming, path/env mapping, engine
// arg vectors, launch script) — desktop/src/main/sandbox-command.
import { test, expect } from "bun:test";
import {
  DEFAULT_SANDBOX_PORTS,
  SANDBOX_AUTH_VOLUME,
  SANDBOX_CREDENTIALS_FILE,
  SANDBOX_HOME,
  SANDBOX_RUN_DIR,
  SANDBOX_WORK_DIR,
  buildAuthCommand,
  buildAuthProbeArgs,
  buildCreateArgs,
  buildExecCommand,
  buildLaunchScript,
  containerNameFor,
  isSandboxContainerName,
  mapHostPathToContainer,
  normalizeProjectDir,
  rewriteLoopbackForContainer,
  sandboxifyEnv,
  shQuote,
} from "../desktop/src/main/sandbox-command.ts";

test("containerNameFor is deterministic and shape-valid", () => {
  const a = containerNameFor("/home/op/proj", "linux");
  expect(a).toBe(containerNameFor("/home/op/proj/", "linux"));
  expect(isSandboxContainerName(a)).toBe(true);
  expect(a).not.toBe(containerNameFor("/home/op/other", "linux"));
});

test("containerNameFor ignores win32 casing and separator style", () => {
  const a = containerNameFor("C:\\Dev\\Proj", "win32");
  expect(a).toBe(containerNameFor("c:\\dev\\proj\\", "win32"));
  expect(isSandboxContainerName(a)).toBe(true);
});

test("isSandboxContainerName rejects anything not generated by us", () => {
  expect(isSandboxContainerName("kory-sbx-0123456789ab")).toBe(true);
  expect(isSandboxContainerName("kory-sbx-0123456789ab; rm -rf /")).toBe(false);
  expect(isSandboxContainerName("kory-sbx-XYZ")).toBe(false);
  expect(isSandboxContainerName("postgres")).toBe(false);
  expect(isSandboxContainerName(42)).toBe(false);
  expect(isSandboxContainerName("kory-sbx-0123456789abc")).toBe(false); // 13 hex
});

test("normalizeProjectDir collapses backslashes and trailing slashes", () => {
  expect(normalizeProjectDir("/a/b//", "linux")).toBe("/a/b");
  expect(normalizeProjectDir("C:\\A\\B", "win32")).toBe("c:/a/b");
});

test("mapHostPathToContainer maps project root, worktrees and out-of-tree", () => {
  expect(mapHostPathToContainer("/home/op/proj", "/home/op/proj", "linux")).toBe(SANDBOX_WORK_DIR);
  expect(
    mapHostPathToContainer("/home/op/proj/.worktrees/fix-1", "/home/op/proj", "linux")
  ).toBe(`${SANDBOX_WORK_DIR}/.worktrees/fix-1`);
  // A sibling dir sharing the prefix must NOT map inside /work.
  expect(mapHostPathToContainer("/home/op/proj-two", "/home/op/proj", "linux")).toBe(
    SANDBOX_WORK_DIR
  );
  // win32: case-insensitive containment, forward-slash tail, casing preserved.
  expect(
    mapHostPathToContainer("C:\\Dev\\Proj\\.worktrees\\Fix", "c:\\dev\\proj", "win32")
  ).toBe(`${SANDBOX_WORK_DIR}/.worktrees/Fix`);
});

test("shQuote survives embedded single quotes", () => {
  expect(shQuote("it's")).toBe(`'it'\\''s'`);
  expect(shQuote("plain")).toBe("'plain'");
});

test("rewriteLoopbackForContainer targets only the host part", () => {
  expect(rewriteLoopbackForContainer("http://127.0.0.1:7899")).toBe(
    "http://host.docker.internal:7899"
  );
  expect(rewriteLoopbackForContainer("http://localhost:3000/x")).toBe(
    "http://host.docker.internal:3000/x"
  );
  expect(rewriteLoopbackForContainer("http://broker.lan:7899")).toBe("http://broker.lan:7899");
  // A loopback literal later in the URL must not be rewritten.
  expect(rewriteLoopbackForContainer("http://broker.lan/api?cb=localhost")).toBe(
    "http://broker.lan/api?cb=localhost"
  );
});

test("buildCreateArgs mounts project, auth volume, run dir and publishes loopback ports", () => {
  const args = buildCreateArgs({
    name: "kory-sbx-0123456789ab",
    image: "koryphaios-sandbox",
    projectDir: "/home/op/proj",
    runDirHost: "/state/sandbox-run",
    peersDirHost: "/home/op/.claude/peers",
    ports: [3000, 3000, -1, 70000],
  });
  expect(args[0]).toBe("create");
  expect(args).toContain(`${SANDBOX_AUTH_VOLUME}:${SANDBOX_HOME}/.claude`);
  expect(args).toContain(`/home/op/proj:${SANDBOX_WORK_DIR}`);
  expect(args).toContain(`/state/sandbox-run:${SANDBOX_RUN_DIR}`);
  expect(args).toContain(`/home/op/.claude/peers:${SANDBOX_HOME}/.claude/peers`);
  expect(args).toContain("kory.project=/home/op/proj");
  // dedup + bounds on ports; loopback-only publish.
  expect(args.filter((a) => a === "-p")).toHaveLength(1);
  expect(args).toContain("127.0.0.1:3000:3000");
  // idles on sleep infinity
  expect(args.slice(-2).join(" ")).toBe("sleep infinity");
});

test("buildCreateArgs skips the peers mount when unset and falls back on ports", () => {
  const args = buildCreateArgs({
    name: "kory-sbx-0123456789ab",
    image: "img",
    projectDir: "/p",
    runDirHost: "/r",
    ports: DEFAULT_SANDBOX_PORTS,
  });
  expect(args.join(" ")).not.toContain(".claude/peers");
  expect(args.filter((a) => a === "-p")).toHaveLength(DEFAULT_SANDBOX_PORTS.length);
});

test("buildLaunchScript exports env, cds and execs — hostile keys dropped", () => {
  const script = buildLaunchScript({
    command: 'claude --session-id "abc"',
    cwd: "/work/.worktrees/fix",
    env: {
      CLAUDE_PEERS_DESK_SESSION: "tile-1",
      "BAD KEY; rm": "x",
      QUOTED: "it's",
    },
  });
  const lines = script.trim().split("\n");
  expect(lines[0]).toBe("#!/bin/bash -l");
  expect(script).toContain(`export CLAUDE_PEERS_DESK_SESSION='tile-1'`);
  expect(script).toContain(`export QUOTED='it'\\''s'`);
  expect(script).not.toContain("BAD KEY");
  expect(script).toContain(`cd '/work/.worktrees/fix' || exit 1`);
  expect(lines[lines.length - 1]).toBe(`exec claude --session-id "abc"`);
});

test("sandboxifyEnv translates the FORCE_GROUP file transport inline", () => {
  const env = {
    CLAUDE_PEERS_FORCE_GROUP_NAME: "deck scope",
    CLAUDE_PEERS_FORCE_GROUP_FILE: "/tmp/secret-600",
    CLAUDE_PEERS_FORCE_GROUP: "",
    CLAUDE_DECK_DESIGN_URL: "http://127.0.0.1:4455",
    OTHER: "v",
  };
  const out = sandboxifyEnv(env, (p) => (p === "/tmp/secret-600" ? "s3cret" : null));
  expect(out.CLAUDE_PEERS_FORCE_GROUP).toBe("s3cret");
  expect(out.CLAUDE_PEERS_FORCE_GROUP_FILE).toBeUndefined();
  expect(out.CLAUDE_DECK_DESIGN_URL).toBe("http://host.docker.internal:4455");
  expect(out.OTHER).toBe("v");
  expect(out.CLAUDE_PEERS_FORCE_GROUP_NAME).toBe("deck scope");
});

test("sandboxifyEnv keeps the inline transport when no file is involved", () => {
  const out = sandboxifyEnv(
    { CLAUDE_PEERS_FORCE_GROUP: "inline", CLAUDE_PEERS_FORCE_GROUP_FILE: "" },
    () => null
  );
  expect(out.CLAUDE_PEERS_FORCE_GROUP).toBe("inline");
  expect(out.CLAUDE_PEERS_FORCE_GROUP_FILE).toBeUndefined();
});

test("sandboxifyEnv drops the group var when the secret file is unreadable", () => {
  const out = sandboxifyEnv(
    { CLAUDE_PEERS_FORCE_GROUP_FILE: "/gone", CLAUDE_PEERS_FORCE_GROUP: "" },
    () => null
  );
  expect(out.CLAUDE_PEERS_FORCE_GROUP).toBeUndefined();
  expect(out.CLAUDE_PEERS_FORCE_GROUP_FILE).toBeUndefined();
});

test("exec/auth/probe command shapes", () => {
  expect(buildExecCommand("docker", "kory-sbx-0123456789ab", "sid")).toBe(
    `docker exec -it kory-sbx-0123456789ab bash ${SANDBOX_RUN_DIR}/cmd-sid.sh`
  );
  expect(buildAuthCommand("podman", "kory-sbx-0123456789ab")).toBe(
    "podman exec -it kory-sbx-0123456789ab bash -lc claude"
  );
  expect(buildAuthProbeArgs("kory-sbx-0123456789ab")).toEqual([
    "exec",
    "kory-sbx-0123456789ab",
    "test",
    "-s",
    SANDBOX_CREDENTIALS_FILE,
  ]);
});
