// PLAN-SANDBOX SBX1: pure sandbox builders (naming, path/env mapping, engine
// arg vectors, launch script) — desktop/src/main/sandbox-command.
import { test, expect } from "bun:test";
import {
  DEFAULT_SANDBOX_PORTS,
  SANDBOX_AUTH_VOLUME,
  SANDBOX_CREDENTIALS_FILE,
  SANDBOX_HOME,
  SANDBOX_RUN_DIR,
  SANDBOX_WORK_DIR,
  buildAuthCommand,
  buildAuthProbeArgs,
  buildAuthPurgeArgs,
  buildBrokerProbeArgs,
  buildImageRemoveArgs,
  buildCopyIntoArgs,
  buildProjectionChownArgs,
  buildProjectionCleanArgs,
  composeCustomDockerfile,
  SANDBOX_IMAGE_CUSTOM,
  SANDBOX_IMAGE_DEFAULT,
  buildCreateArgs,
  buildExecCommand,
  buildImageBuildCommand,
  buildImageProbeArgs,
  buildLaunchScript,
  buildSupervisorExecArgs,
  containerNameFor,
  containerTranscriptDir,
  isSandboxContainerName,
  mapHostPathToContainer,
  normalizeProjectDir,
  parseTranscriptList,
  rewriteLoopbackForContainer,
  rewritePluginDirForContainer,
  SANDBOX_DECK_PLUGIN_DIR,
  SANDBOX_DECK_PLUGIN_NAME,
  sandboxifyEnv,
  shQuote,
} from "../desktop/src/main/sandbox-command.ts";
import { DECK_PLUGIN_DIRNAME, deckPluginDirFor } from "../desktop/src/main/session-command.ts";
import { basename } from "node:path";

test("containerNameFor is deterministic and shape-valid", () => {
  const a = containerNameFor("/home/op/proj", "linux");
  expect(a).toBe(containerNameFor("/home/op/proj/", "linux"));
  expect(isSandboxContainerName(a)).toBe(true);
  expect(a).not.toBe(containerNameFor("/home/op/other", "linux"));
});

test("containerNameFor ignores win32 casing and separator style", () => {
  const a = containerNameFor("C:\\Dev\\Proj", "win32");
  expect(a).toBe(containerNameFor("c:\\dev\\proj\\", "win32"));
  expect(isSandboxContainerName(a)).toBe(true);
});

test("isSandboxContainerName rejects anything not generated by us", () => {
  expect(isSandboxContainerName("kory-sbx-0123456789ab")).toBe(true);
  expect(isSandboxContainerName("kory-sbx-0123456789ab; rm -rf /")).toBe(false);
  expect(isSandboxContainerName("kory-sbx-XYZ")).toBe(false);
  expect(isSandboxContainerName("postgres")).toBe(false);
  expect(isSandboxContainerName(42)).toBe(false);
  expect(isSandboxContainerName("kory-sbx-0123456789abc")).toBe(false); // 13 hex
});

test("normalizeProjectDir collapses backslashes and trailing slashes", () => {
  expect(normalizeProjectDir("/a/b//", "linux")).toBe("/a/b");
  expect(normalizeProjectDir("C:\\A\\B", "win32")).toBe("c:/a/b");
});

test("mapHostPathToContainer maps project root, worktrees and out-of-tree", () => {
  expect(mapHostPathToContainer("/home/op/proj", "/home/op/proj", "linux")).toBe(SANDBOX_WORK_DIR);
  expect(
    mapHostPathToContainer("/home/op/proj/.worktrees/fix-1", "/home/op/proj", "linux")
  ).toBe(`${SANDBOX_WORK_DIR}/.worktrees/fix-1`);
  // A sibling dir sharing the prefix must NOT map inside /work (null, see the
  // dedicated test below).
  expect(mapHostPathToContainer("/home/op/proj-two", "/home/op/proj", "linux")).toBeNull();
  // win32: case-insensitive containment, forward-slash tail, casing preserved.
  expect(
    mapHostPathToContainer("C:\\Dev\\Proj\\.worktrees\\Fix", "c:\\dev\\proj", "win32")
  ).toBe(`${SANDBOX_WORK_DIR}/.worktrees/Fix`);
});

test("mapHostPathToContainer returns NULL outside the mount, never a /work fallback", () => {
  // Falling back to /work silently ran the agent in a different directory than
  // asked. A symlinked project prefix (macOS /var) did exactly that to every
  // worktree session, so the mapper must refuse instead.
  expect(mapHostPathToContainer("/home/op/other", "/home/op/proj", "linux")).toBeNull();
  expect(mapHostPathToContainer("/home/op/proj-two", "/home/op/proj", "linux")).toBeNull();
  expect(mapHostPathToContainer("/private/var/p/.worktrees/x", "/var/p", "linux")).toBeNull();
  // …and containerTranscriptDir propagates that as "unknown", not "no transcript".
  expect(containerTranscriptDir("/home/op/other", "/home/op/proj", "linux")).toBeNull();
});

test("shQuote survives embedded single quotes", () => {
  expect(shQuote("it's")).toBe(`'it'\\''s'`);
  expect(shQuote("plain")).toBe("'plain'");
});

// Card a79c7696 volet 1: wrap() left --plugin-dir pointing at a HOST path
// inside the container. The coverage trap the card calls out: a test that
// only checks the flag CHANGED would still pass if it pointed at an empty
// dir. So this pins the rewritten value against SANDBOX_HOME composed
// independently, not just against SANDBOX_DECK_PLUGIN_DIR re-imported --
// proving the flag lands exactly where projectDeckPlugin() (sandbox-service)
// copies deck-plugin to.
test("rewritePluginDirForContainer redirects --plugin-dir onto the projected container path", () => {
  const hostCmd = `claude --plugin-dir "C:\\Users\\op\\AppData\\Local\\Programs\\koryphaios\\resources\\deck-plugin" --session-id "abc"`;
  expect(rewritePluginDirForContainer(hostCmd)).toBe(
    `claude --plugin-dir "${SANDBOX_HOME}/.claude/deck-plugin" --session-id "abc"`
  );
  expect(SANDBOX_DECK_PLUGIN_DIR).toBe(`${SANDBOX_HOME}/.claude/deck-plugin`);
});

test("rewritePluginDirForContainer is a no-op when --plugin-dir is absent", () => {
  const hostCmd = `claude --session-id "abc"`;
  expect(rewritePluginDirForContainer(hostCmd)).toBe(hostCmd);
});

// Reviewer (card a79c7696 volet 1 review, correction 2): the invariant has a
// THIRD corner beyond SANDBOX_DECK_PLUGIN_DIR (what --plugin-dir is rewritten
// to) -- the literal ProjectionEntry.name driving clean/chown in
// sandbox-service.ts, and the basename getDeckPluginDir actually resolves on
// the HOST (what docker cp really copies, so what `basename(src)` really
// lands as under SANDBOX_CONFIG_DIR/). Before this test, all three were
// separate 'deck-plugin' literals pinned only by comment; a rename of ONE
// would leave the other two -- and every existing test here -- green.
test("SANDBOX_DECK_PLUGIN_NAME matches the host basename deckPluginDirFor actually resolves", () => {
  expect(SANDBOX_DECK_PLUGIN_NAME).toBe(DECK_PLUGIN_DIRNAME);
  expect(basename(deckPluginDirFor(true, "/resources", "/repo"))).toBe(SANDBOX_DECK_PLUGIN_NAME);
  expect(basename(deckPluginDirFor(false, "/resources", "/repo"))).toBe(SANDBOX_DECK_PLUGIN_NAME);
});

test("rewriteLoopbackForContainer targets only the host part", () => {
  expect(rewriteLoopbackForContainer("http://127.0.0.1:7899")).toBe(
    "http://host.docker.internal:7899"
  );
  expect(rewriteLoopbackForContainer("http://localhost:3000/x")).toBe(
    "http://host.docker.internal:3000/x"
  );
  expect(rewriteLoopbackForContainer("http://broker.lan:7899")).toBe("http://broker.lan:7899");
  // A loopback literal later in the URL must not be rewritten.
  expect(rewriteLoopbackForContainer("http://broker.lan/api?cb=localhost")).toBe(
    "http://broker.lan/api?cb=localhost"
  );
});

test("buildCreateArgs mounts project, auth volume, run dir and publishes loopback ports", () => {
  const args = buildCreateArgs({
    name: "kory-sbx-0123456789ab",
    image: "koryphaios-sandbox",
    projectDir: "/home/op/proj",
    runDirHost: "/state/sandbox-run",
    peersDirHost: "/home/op/.claude/peers",
    ports: [3000, 3000, -1, 70000],
  });
  expect(args[0]).toBe("create");
  expect(args).toContain(`${SANDBOX_AUTH_VOLUME}:${SANDBOX_HOME}/.claude`);
  expect(args).toContain(`/home/op/proj:${SANDBOX_WORK_DIR}`);
  expect(args).toContain(`/state/sandbox-run:${SANDBOX_RUN_DIR}`);
  expect(args).toContain(`/home/op/.claude/peers:${SANDBOX_HOME}/.claude/peers`);
  expect(args).toContain("kory.project=/home/op/proj");
  // dedup + bounds on ports; loopback-only publish.
  expect(args.filter((a) => a === "-p")).toHaveLength(1);
  expect(args).toContain("127.0.0.1:3000:3000");
  // idles on sleep infinity
  expect(args.slice(-2).join(" ")).toBe("sleep infinity");
});

test("buildCreateArgs skips the peers mount when unset and falls back on ports", () => {
  const args = buildCreateArgs({
    name: "kory-sbx-0123456789ab",
    image: "img",
    projectDir: "/p",
    runDirHost: "/r",
    ports: DEFAULT_SANDBOX_PORTS,
  });
  expect(args.join(" ")).not.toContain(".claude/peers");
  expect(args.filter((a) => a === "-p")).toHaveLength(DEFAULT_SANDBOX_PORTS.length);
});

test("buildCreateArgs renders protection.applied as :ro binds, sorted by containerPath length, after /work", () => {
  const args = buildCreateArgs({
    name: "kory-sbx-0123456789ab",
    image: "img",
    projectDir: "/home/op/proj",
    runDirHost: "/r",
    ports: [],
    protection: {
      status: "applied",
      applied: [
        {
          rel: ".claude/agents",
          kind: "dir",
          hostPath: "/home/op/proj/.claude/agents",
          containerPath: `${SANDBOX_WORK_DIR}/.claude/agents`
        },
        {
          rel: ".mcp.json",
          kind: "file",
          hostPath: "/home/op/proj/.mcp.json",
          containerPath: `${SANDBOX_WORK_DIR}/.mcp.json`
        }
      ],
      skipped: []
    }
  });

  const workIdx = args.indexOf(`/home/op/proj:${SANDBOX_WORK_DIR}`);
  const mcpIdx = args.indexOf(`/home/op/proj/.mcp.json:${SANDBOX_WORK_DIR}/.mcp.json:ro`);
  const agentsIdx = args.indexOf(`/home/op/proj/.claude/agents:${SANDBOX_WORK_DIR}/.claude/agents:ro`);
  expect(workIdx).toBeGreaterThanOrEqual(0);
  expect(mcpIdx).toBeGreaterThan(workIdx);
  // .mcp.json's containerPath is shorter than .claude/agents's -> emitted first.
  expect(mcpIdx).toBeLessThan(agentsIdx);
  // Every protection bind must be read-only, never rw.
  for (const idx of [mcpIdx, agentsIdx]) {
    expect(args[idx]?.endsWith(":ro")).toBe(true);
  }
});

test("buildCreateArgs emits nothing extra when protection is not-applicable or absent", () => {
  const withoutProtection = buildCreateArgs({
    name: "kory-sbx-0123456789ab",
    image: "img",
    projectDir: "/p",
    runDirHost: "/r",
    ports: []
  });
  const notApplicable = buildCreateArgs({
    name: "kory-sbx-0123456789ab",
    image: "img",
    projectDir: "/p",
    runDirHost: "/r",
    ports: [],
    protection: { status: "not-applicable", reason: "copy-mode", applied: [], skipped: [] }
  });
  expect(withoutProtection.filter((a) => a === "-v")).toHaveLength(3);
  expect(notApplicable.filter((a) => a === "-v")).toHaveLength(3);
});

test("buildLaunchScript exports env, cds and execs — hostile keys dropped", () => {
  const script = buildLaunchScript({
    command: 'claude --session-id "abc"',
    cwd: "/work/.worktrees/fix",
    env: {
      CLAUDE_PEERS_DESK_SESSION: "tile-1",
      "BAD KEY; rm": "x",
      QUOTED: "it's",
    },
  });
  const lines = script.trim().split("\n");
  expect(lines[0]).toBe("#!/bin/bash -l");
  expect(script).toContain(`export CLAUDE_PEERS_DESK_SESSION='tile-1'`);
  expect(script).toContain(`export QUOTED='it'\\''s'`);
  expect(script).not.toContain("BAD KEY");
  expect(script).toContain(`cd '/work/.worktrees/fix' || exit 1`);
  expect(lines[lines.length - 1]).toBe(`exec claude --session-id "abc"`);
});

test("sandboxifyEnv translates the FORCE_GROUP file transport inline", () => {
  const env = {
    CLAUDE_PEERS_FORCE_GROUP_NAME: "deck scope",
    CLAUDE_PEERS_FORCE_GROUP_FILE: "/tmp/secret-600",
    CLAUDE_PEERS_FORCE_GROUP: "",
    CLAUDE_DECK_DESIGN_URL: "http://127.0.0.1:4455",
    OTHER: "v",
  };
  const out = sandboxifyEnv(env, (p) => (p === "/tmp/secret-600" ? "s3cret" : null));
  expect(out.CLAUDE_PEERS_FORCE_GROUP).toBe("s3cret");
  expect(out.CLAUDE_PEERS_FORCE_GROUP_FILE).toBeUndefined();
  expect(out.CLAUDE_DECK_DESIGN_URL).toBe("http://host.docker.internal:4455");
  expect(out.OTHER).toBe("v");
  expect(out.CLAUDE_PEERS_FORCE_GROUP_NAME).toBe("deck scope");
});

// The CLI keeps its ONBOARDING state in .claude.json, which by default sits
// beside the config dir, in $HOME -- outside the shared auth volume. Left
// alone, a login done in the throwaway auth container dies with it and the
// agent greets the operator with "Select login method" although the volume
// holds valid credentials. Forcing the config root onto the mounted dir is
// what makes one login serve every container.
test("sandboxifyEnv forces the config root onto the shared volume", () => {
  expect(sandboxifyEnv({}, () => null).CLAUDE_CONFIG_DIR).toBe("/home/kory/.claude");
  // A host value is a Windows path here: it must never win.
  const out = sandboxifyEnv({ CLAUDE_CONFIG_DIR: "C:/Users/x/.claude" }, () => null);
  expect(out.CLAUDE_CONFIG_DIR).toBe("/home/kory/.claude");
});

// `docker cp` copies a symlink AS a symlink. Operators commonly keep
// ~/.claude/CLAUDE.md and friends as links into a config repo, so without -L
// the container received dangling links to host paths and the global config
// was silently missing from every sandboxed agent.
test("config projection follows source symlinks", () => {
  expect(buildCopyIntoArgs("kory-sbx-0123456789ab", "/host/CLAUDE.md", "/home/kory/.claude/")).toEqual([
    "cp",
    "-L",
    "/host/CLAUDE.md",
    "kory-sbx-0123456789ab:/home/kory/.claude/",
  ]);
});

// Custom image (f29b1917): the operator's fragment rides on top of the fixed
// base. FROM is refused rather than honoured — the base is the app's contract
// (user kory, CLAUDE_CONFIG_DIR, the CLI preinstalled).
test("composeCustomDockerfile pins the base image and refuses FROM lines", () => {
  const composed = composeCustomDockerfile("RUN sudo apt-get install -y jq\n");
  expect(composed).toContain(`FROM ${SANDBOX_IMAGE_DEFAULT}\n`);
  expect(composed!.endsWith("RUN sudo apt-get install -y jq\n")).toBe(true);
  // Empty/blank fragment: nothing to build.
  expect(composeCustomDockerfile("")).toBeNull();
  expect(composeCustomDockerfile("   \n  ")).toBeNull();
  // A fragment smuggling its own FROM (any case, any line) is refused.
  expect(() => composeCustomDockerfile("from alpine\nRUN true")).toThrow("custom-fragment-from");
  expect(() => composeCustomDockerfile("RUN true\nFROM scratch")).toThrow("custom-fragment-from");
  // The custom tag stays derived from the default one (shared/types is the
  // canonical copy the Docker view reads).
  expect(SANDBOX_IMAGE_CUSTOM).toBe(`${SANDBOX_IMAGE_DEFAULT}-custom`);
});

// `docker cp -L` overwrites destination FILES but will not replace a
// destination DIRECTORY SYMLINK: the auth volume kept `agents`/`skills` as
// dangling links from a pre-`-L` copy, and the projection reported success
// while the operator's global agents/skills stayed absent from every
// container. The purge that precedes the copies is what makes them land.
test("projection pre-clean removes exactly the entries about to be copied", () => {
  // --user root: docker cp lands the trees as root, and kory can unlink the
  // top-level entries (it owns ~/.claude) but nothing inside a root-owned dir
  // (the first kory run sprayed "rm: Permission denied" over plugins/).
  expect(
    buildProjectionCleanArgs("kory-sbx-0123456789ab", ["CLAUDE.md", "agents", "skills"])
  ).toEqual([
    "exec",
    "--user",
    "root",
    "kory-sbx-0123456789ab",
    "rm",
    "-rf",
    "/home/kory/.claude/CLAUDE.md",
    "/home/kory/.claude/agents",
    "/home/kory/.claude/skills",
  ]);
  // The post-copy chown hands the root-owned copies to the container user, so
  // the CLI can maintain them (installed_plugins.json was read-only for it).
  expect(buildProjectionChownArgs("kory-sbx-0123456789ab", ["plugins", "../evil"])).toEqual([
    "exec",
    "--user",
    "root",
    "kory-sbx-0123456789ab",
    "chown",
    "-R",
    "kory:kory",
    "/home/kory/.claude/plugins",
  ]);
  // Boundary re-check: an entry name carrying a path separator (or a bare
  // `..`, which the charset alone would accept and turn into
  // `rm -rf ~/.claude/..`) must never reach the container's rm — the
  // allow-list is flat names only.
  expect(
    buildProjectionCleanArgs("kory-sbx-0123456789ab", ["../peers", "a/b", "..", ".", "ok.md"])
  ).toEqual([
    "exec",
    "--user",
    "root",
    "kory-sbx-0123456789ab",
    "rm",
    "-rf",
    "/home/kory/.claude/ok.md",
  ]);
});

test("sandboxifyEnv keeps the inline transport when no file is involved", () => {
  const out = sandboxifyEnv(
    { CLAUDE_PEERS_FORCE_GROUP: "inline", CLAUDE_PEERS_FORCE_GROUP_FILE: "" },
    () => null
  );
  expect(out.CLAUDE_PEERS_FORCE_GROUP).toBe("inline");
  expect(out.CLAUDE_PEERS_FORCE_GROUP_FILE).toBeUndefined();
});

test("sandboxifyEnv drops the group var when the secret file is unreadable", () => {
  const out = sandboxifyEnv(
    { CLAUDE_PEERS_FORCE_GROUP_FILE: "/gone", CLAUDE_PEERS_FORCE_GROUP: "" },
    () => null
  );
  expect(out.CLAUDE_PEERS_FORCE_GROUP).toBeUndefined();
  expect(out.CLAUDE_PEERS_FORCE_GROUP_FILE).toBeUndefined();
});

test("containerTranscriptDir encodes the CONTAINER cwd, not the host one", () => {
  // Claude keys transcripts by cwd; inside the sandbox that cwd is /work/...
  // so encoding the host path would look in a dir that never exists.
  expect(containerTranscriptDir("/home/op/proj", "/home/op/proj", "linux")).toBe(
    `${SANDBOX_HOME}/.claude/projects/-work`
  );
  expect(
    containerTranscriptDir("/home/op/proj/.worktrees/fix", "/home/op/proj", "linux")
  ).toBe(`${SANDBOX_HOME}/.claude/projects/-work--worktrees-fix`);
  expect(containerTranscriptDir("C:\\Dev\\Proj", "c:\\dev\\proj", "win32")).toBe(
    `${SANDBOX_HOME}/.claude/projects/-work`
  );
});

test("parseTranscriptList reads find's name/mtime rows and ignores noise", () => {
  const out = parseTranscriptList("a.jsonl\t1700000000.5\nb.jsonl\t1700000100\nnope.txt\t1\n\n");
  expect(out).toEqual([
    { id: "a", mtimeMs: 1700000000500 },
    { id: "b", mtimeMs: 1700000100000 }
  ]);
  expect(parseTranscriptList("")).toEqual([]);
  // A row without a parsable stamp still yields the id (mtime 0 = oldest).
  expect(parseTranscriptList("c.jsonl\tx")).toEqual([{ id: "c", mtimeMs: 0 }]);
});

test("supervisor exec keeps the agent command as ONE argv element", () => {
  const args = buildSupervisorExecArgs("kory-sbx-0123456789ab", 'bun add zod && echo "$HOME"');
  // The whole command is a single element: nothing can break out into the
  // HOST command line (hostile input #4). bash inside the container is the
  // intended interpreter — that is what a sandbox is for.
  expect(args).toEqual([
    "exec",
    "-w",
    SANDBOX_WORK_DIR,
    "kory-sbx-0123456789ab",
    "bash",
    "-lc",
    'bun add zod && echo "$HOME"'
  ]);
});

test("image build/probe and docker cp shapes", () => {
  expect(buildImageBuildCommand("docker", "koryphaios-sandbox", "/res/sandbox")).toBe(
    "docker build -t 'koryphaios-sandbox' '/res/sandbox'"
  );
  // A path with a quote cannot break out of the build command line.
  expect(buildImageBuildCommand("podman", "img", "/a'b")).toBe(
    "podman build -t 'img' '/a'\\''b'"
  );
  expect(buildImageProbeArgs("img")).toEqual(["image", "inspect", "--format", "{{.Created}}", "img"]);
  expect(buildCopyIntoArgs("kory-sbx-0123456789ab", "/home/op/.claude/agents", "/home/kory/.claude/")).toEqual([
    "cp",
    "-L",
    "/home/op/.claude/agents",
    "kory-sbx-0123456789ab:/home/kory/.claude/"
  ]);
});

test("broker probe curls /health from inside the container", () => {
  expect(buildBrokerProbeArgs("kory-sbx-0123456789ab", "http://host.docker.internal:7899")).toEqual([
    "exec",
    "kory-sbx-0123456789ab",
    "curl",
    "-sf",
    "-m",
    "4",
    "-o",
    "/dev/null",
    "http://host.docker.internal:7899/health"
  ]);
});

test("buildCreateArgs mounts the CLONE in copy mode, labels the real project", () => {
  const args = buildCreateArgs({
    name: "kory-sbx-0123456789ab",
    image: "img",
    projectDir: "/home/op/proj",
    workSource: "/state/sandbox-copies/kory-sbx-0123456789ab",
    runDirHost: "/state/sandbox-run",
    ports: [3000]
  });
  expect(args).toContain(`/state/sandbox-copies/kory-sbx-0123456789ab:${SANDBOX_WORK_DIR}`);
  expect(args).not.toContain(`/home/op/proj:${SANDBOX_WORK_DIR}`);
  // Identity still points at the real project (the rail view labels rows by it).
  expect(args).toContain("kory.project=/home/op/proj");
});

test("exec command shape", () => {
  expect(buildExecCommand("docker", "kory-sbx-0123456789ab", "sid")).toBe(
    `docker exec -it kory-sbx-0123456789ab bash ${SANDBOX_RUN_DIR}/cmd-sid.sh`
  );
});

// The credentials volume is app-wide: every operation on it runs in a
// throwaway container built from the (also app-wide) image, mounting NOTHING
// but kory-claude-auth. No project container is named anywhere -- that coupling
// is exactly what made "sign in" impossible before a project container existed.
test("auth commands run in a throwaway container, not the project one", () => {
  // The config-root env travels with the mount: the login writes .claude.json
  // into the volume, so the next container sees an account, not an onboarding
  // screen.
  const mount = `-v kory-claude-auth:/home/kory/.claude -e CLAUDE_CONFIG_DIR=/home/kory/.claude`;
  expect(buildAuthCommand("podman", "koryphaios-sandbox")).toBe(
    `podman run --rm -it ${mount} koryphaios-sandbox bash -lc claude`
  );
  // The probe demands credentials AND a finished onboarding: probing the
  // credentials alone made the login dialog kill the CLI mid-onboarding
  // (hasCompletedOnboarding never written), so every agent re-ran onboarding
  // while the Docker view claimed "connected". The if/else keeps the exit
  // code binary (a bare grep on a missing .claude.json exits 2 = "unknown").
  expect(buildAuthProbeArgs("koryphaios-sandbox")).toEqual([
    "run",
    "--rm",
    "-v",
    "kory-claude-auth:/home/kory/.claude",
    "-e",
    "CLAUDE_CONFIG_DIR=/home/kory/.claude",
    "koryphaios-sandbox",
    "sh",
    "-c",
    `if test -s ${SANDBOX_CREDENTIALS_FILE} && grep -qs hasCompletedOnboarding /home/kory/.claude/.claude.json; then exit 0; else exit 1; fi`,
  ]);
  expect(buildAuthPurgeArgs("koryphaios-sandbox")).toEqual([
    "run",
    "--rm",
    "-v",
    "kory-claude-auth:/home/kory/.claude",
    "-e",
    "CLAUDE_CONFIG_DIR=/home/kory/.claude",
    "koryphaios-sandbox",
    "rm",
    "-f",
    SANDBOX_CREDENTIALS_FILE,
  ]);
  // The work mount is the one thing that must never appear here.
  expect(buildAuthCommand("docker", "koryphaios-sandbox")).not.toContain("/work");
});

// `image rm` is deliberately unforced: the engine refusing because a container
// still references the image is the honest answer, where -f would orphan those
// containers behind an untagged id.
test("image removal is never forced", () => {
  expect(buildImageRemoveArgs("koryphaios-sandbox")).toEqual([
    "image",
    "rm",
    "koryphaios-sandbox",
  ]);
  expect(buildImageRemoveArgs("koryphaios-sandbox")).not.toContain("-f");
});
