// Companion TLS certificate: load/generate/invalidate (card 3776ae19,
// certificate half). Pure module -- zero RUNTIME import of 'selfsigned' or
// 'electron' (only a type-only import of the former, erased at transpile --
// see the import statement below) -- so bun can collect it in the
// "Bun tests (pure modules)" CI step, which runs BEFORE `npm install` in
// desktop/. 'selfsigned' is resolvable at that point too, from the ROOT
// package.json devDependency this same card added (tests/desktop-companion-
// cert-e2e.test.ts needs it at runtime; this module does not) -- but the
// real generateCert call is still INJECTED by the caller (companion-
// server.ts) as a plain closure regardless, so this module never touches
// the npm package itself even where it could.
//
// The bug this file closes (measured, roadmap card 3776ae19): a certificate
// generated by an OLDER build of companion-server.ts is SHA-1 signed and its
// SAN never carries the LAN IP the server actually serves on (selfsigned's
// own buildExtensions only adds an IP SAN when commonName === 'localhost',
// which this server's commonName never is) -- so the browser warning the
// header comment describes as "once" is in fact PERMANENT. Fixing the
// generation parameters alone has NO EFFECT on a machine that already ran
// the companion server once: the old code read-and-returned any existing
// companion-cert.json unconditionally, before generateCert was ever reached.
// COMPANION_CERT_VERSION below is the invalidation lever: bump it whenever
// the generation parameters change, and loadOrCreateCert regenerates instead
// of serving a stale cert forever.

// Type-only import (erased at transpile -- verified below and in this
// module's own header claim): pulls the extension/altName/attrs shapes from
// selfsigned's OWN .d.ts instead of hand-copying them, so a future selfsigned
// upgrade that adds/renames a field is a compile error here rather than a
// silent divergence (review round, card 3776ae19: a hand-copied CertAltName
// is what let a missing `critical` field go unnoticed -- see buildCertRequest
// below). selfsigned/index.d.ts declares these without an explicit `export`
// keyword ahead of its own `export declare function generate`, which reads
// as module-private -- but they resolve cleanly under this project's
// `moduleResolution: bundler` (measured: `npm run typecheck:node` reports no
// TS2305/TS2307 for this import, only the ordinary "unused" diagnostic
// before these names were referenced below).
import type { CertificateExtension, CertificateField, SelfsignedOptions, SubjectAltNameEntry } from 'selfsigned'

/** Bump whenever buildCertRequest's output (or generation parameters in
 * general) change in a way that must invalidate an already-persisted cert.
 * Bumped 2026-08-31 (card 3776ae19): SHA-256 signature + LAN-IP SAN. */
export const COMPANION_CERT_VERSION = 2

export interface CertMaterial {
  key: string
  cert: string
}

interface StoredCert extends CertMaterial {
  /** Absent on every cert this repo ever generated before this card --
   * treated the same as an explicit stale version. */
  version?: number
  /** The LAN address the cert's SAN was generated for. Review round: a cert
   * whose version still matches but whose SAN carries an address the server
   * no longer binds to (LAN change, DHCP renewal) is just as stale as a
   * version mismatch -- both leave the browser warning permanent, which is
   * this whole card's point. Absent on every cert generated before this
   * field existed, same treatment as a missing `version`. */
  addr?: string
}

/** The subset of node:fs this module needs, injected so callers can stub it
 * in tests without touching the real filesystem (or pass the real module). */
export interface CertFs {
  existsSync: (path: string) => boolean
  readFileSync: (path: string, encoding: 'utf8') => string
  writeFileSync: (path: string, data: string, options: { mode: number }) => void
}

/**
 * Load the persisted cert at `file`, or generate (via the injected
 * `generate`) and persist a fresh one when the file is absent, unreadable,
 * or its stored version/address does not match `currentVersion`/`currentAddr`.
 * Required params (no defaults) on purpose: this is a security-relevant
 * gate, every call site states its fs/error-sink/version/address explicitly
 * rather than inheriting a silent default.
 *
 * `currentAddr` (review round, card 3776ae19): a cert generated for an
 * OLDER LAN address (the operator's network changed, a DHCP lease renewed)
 * is stale for the same externally-visible reason a version mismatch is --
 * its SAN no longer matches the host the server actually serves on, and the
 * browser warning goes permanent again. Regenerating on address change costs
 * no pairing that would otherwise have survived: companion-server.ts binds
 * with `server.listen(0, lanAddr)`, so the PORT (part of the origin
 * paired-hosts.ts keys a pairing by) already changes on every server start
 * regardless of this field.
 *
 * Non-fatal by design, matching the pre-existing behaviour this replaces:
 * an unreadable/corrupt stored file falls through to generation (reported
 * via `onError`, not thrown), and a persistence failure after a successful
 * generation still returns the fresh material to the caller so the server
 * still starts. A `generate()` rejection is NOT caught here -- it propagates
 * to the caller, since returning a corrupt/partial material object would be
 * strictly worse than failing loudly.
 */
export async function loadOrCreateCert(
  file: string,
  generate: () => Promise<CertMaterial> | CertMaterial,
  currentVersion: number,
  currentAddr: string,
  fs: CertFs,
  onError: (msg: string, err: unknown) => void
): Promise<CertMaterial> {
  try {
    if (fs.existsSync(file)) {
      const parsed = JSON.parse(fs.readFileSync(file, 'utf8')) as StoredCert
      if (parsed.key && parsed.cert && parsed.version === currentVersion && parsed.addr === currentAddr) {
        return { key: parsed.key, cert: parsed.cert }
      }
    }
  } catch (err) {
    onError('persisted cert unreadable — regenerating', err)
  }
  const material = await generate()
  const stored: StoredCert = { ...material, version: currentVersion, addr: currentAddr }
  try {
    fs.writeFileSync(file, JSON.stringify(stored), { mode: 0o600 })
  } catch (err) {
    // Non-fatal: the server still runs with the freshly generated material,
    // the browser warning (or the next launch's regeneration cost) just
    // repeats. Traced (no-silent-errors rule), never thrown.
    onError('cert persistence failed', err)
  }
  return material
}

export type CertAttr = CertificateField
export type CertAltName = SubjectAltNameEntry
export type CertExtension = CertificateExtension

export interface CertGenerateOptions extends SelfsignedOptions {
  keySize: number
  algorithm: 'sha256'
  extensions: CertExtension[]
}

/**
 * The exact selfsigned attrs/options for the companion cert, given the LAN
 * address the server actually binds to.
 *
 * Two measured defects this closes (roadmap card 3776ae19): (a) no
 * `algorithm` option previously meant selfsigned's getAlgorithmName() fell
 * back to its `default:` case, SHA-1; (b) selfsigned only adds an IP SAN
 * entry on its own when commonName === 'localhost', so this server's fixed
 * commonName ('koryphaios-companion') never got one — the served
 * `https://<lanAddr>:<port>` URL never matched the cert.
 *
 * TRAP (measured in selfsigned's buildExtensions, desktop/node_modules/
 * selfsigned/index.js): a non-empty user `extensions` array REPLACES the
 * package's own defaults wholesale rather than merging with them. Passing
 * only a `subjectAltName` entry (the roadmap card's literal suggested form)
 * would therefore silently drop basicConstraints/keyUsage/extKeyUsage —
 * this function replicates that full default set explicitly, and ADDS the
 * IP SAN entry unconditionally (not gated on commonName).
 *
 * SECOND TRAP, review round: replicating the default set is not just the
 * four extension NAMES and their field VALUES -- selfsigned's own defaults
 * (index.js's buildExtensions, the `!userExtensions` branch) also mark
 * basicConstraints and keyUsage CRITICAL (the literal `true` third
 * constructor argument), while extKeyUsage and subjectAltName are NOT
 * (`false`). The user-supplied-extensions branch reads `ext.critical ||
 * false` per entry -- an extension object with no `critical` field silently
 * becomes non-critical, a real (if today inert, since no browser rejects a
 * non-critical keyUsage on a self-signed leaf) divergence from what
 * selfsigned would have produced unassisted. Every entry below states its
 * `critical` value explicitly, matching selfsigned's own defaults exactly,
 * rather than relying on the field's default.
 */
export function buildCertRequest(lanAddr: string): { attrs: CertAttr[]; options: CertGenerateOptions } {
  const commonName = 'koryphaios-companion'
  return {
    attrs: [{ name: 'commonName', value: commonName }],
    options: {
      keySize: 2048,
      algorithm: 'sha256',
      extensions: [
        { name: 'basicConstraints', cA: false, critical: true },
        { name: 'keyUsage', digitalSignature: true, keyEncipherment: true, critical: true },
        { name: 'extKeyUsage', serverAuth: true, clientAuth: true, critical: false },
        {
          name: 'subjectAltName',
          critical: false,
          altNames: [
            { type: 2, value: commonName },
            { type: 7, ip: lanAddr }
          ]
        }
      ]
    }
  }
}
