// Sandbox mode (PLAN-SANDBOX SBX1): pure builders for everything the Docker/
// Podman integration interpolates into a command line — container naming,
// host→container path mapping, engine CLI argument vectors, the per-session
// launch script and the `exec` wrapper. Node builtins only (no electron, no
// child_process) so the whole quoting/mapping surface is bun-testable.
//
// SECURITY (CLAUDE.md hostile inputs #3/#4): every consumer passes container
// names through isSandboxContainerName() before they reach the engine CLI, and
// the launch script is written to a Deck-owned run dir — the session command
// itself never travels through a PowerShell→bash quoting boundary (the script
// file IS the boundary).

import { createHash } from 'node:crypto'
import { platform } from 'node:os'
import { encodeProjectDir } from './session-transcript'
import { DECK_PLUGIN_DIRNAME } from './session-command'
import type { ProtectionPlan } from './sandbox-protect'

export type SandboxEngine = 'docker' | 'podman'

/** Named volume carrying ~/.claude (credentials + CLI state) across containers. */
export const SANDBOX_AUTH_VOLUME = 'kory-claude-auth'
/** Image the operator builds from desktop/resources/sandbox/Dockerfile. */
export { SANDBOX_IMAGE_DEFAULT_TAG as SANDBOX_IMAGE_DEFAULT } from '../shared/types'
import { SANDBOX_IMAGE_DEFAULT_TAG as SANDBOX_IMAGE_DEFAULT } from '../shared/types'
/**
 * Tag of the operator-customised image (f29b1917): built from a generated
 * `FROM koryphaios-sandbox` + the operator's Dockerfile fragment. Always
 * derived from the DEFAULT base tag, never from the project's configured
 * image — deriving from `image()` would loop the day a project already points
 * at the custom tag. Canonical value lives in shared/types.ts (the Docker
 * view needs it too); re-exported here like the PTY ids above.
 */
export { SANDBOX_IMAGE_CUSTOM_TAG as SANDBOX_IMAGE_CUSTOM } from '../shared/types'

/**
 * Validate the operator's Dockerfile fragment and compose the full custom
 * Dockerfile. A FROM line is refused rather than honoured: the base is the
 * app's contract (user kory, CLAUDE_CONFIG_DIR, the CLI preinstalled) and a
 * fragment silently swapping it would produce containers that fail far from
 * the cause. Returns null for an empty/blank fragment (nothing to build).
 * The fragment is OPERATOR app-state input (never repo-provided), so this is
 * a UX guard, not a security boundary.
 */
export function composeCustomDockerfile(fragment: string): string | null {
  const trimmed = fragment.trim()
  if (!trimmed) return null
  if (/^\s*FROM\b/im.test(trimmed)) throw new Error('custom-fragment-from')
  return `# Generated by Koryphaios — operator customisation on top of the base image.\nFROM ${SANDBOX_IMAGE_DEFAULT}\n${trimmed}\n`
}
/** Mount point of the project dir inside the container. */
export const SANDBOX_WORK_DIR = '/work'
/** Mount point of the Deck-owned run dir (launch scripts) inside the container. */
export const SANDBOX_RUN_DIR = '/kory-run'
/** Home of the container user (Dockerfile: `kory`). */
export const SANDBOX_USER = 'kory'
export const SANDBOX_HOME = `/home/${SANDBOX_USER}`

/**
 * The CLI writes onboarding state to .claude.json beside $HOME by default,
 * separate from the credentials dir — so a login in the throwaway auth
 * container never reaches the project container, which still shows the login
 * screen despite a connected volume.
 * Setting CLAUDE_CONFIG_DIR to the mounted dir moves .claude.json inside it
 * too, so login state travels with the credentials; must be exported for both
 * the auth container and every session.
 */
export const SANDBOX_CONFIG_DIR = `${SANDBOX_HOME}/.claude`
export const SANDBOX_CONFIG_DIR_ENV = `CLAUDE_CONFIG_DIR=${SANDBOX_CONFIG_DIR}`
/** Credentials file probed to decide "authenticated" (revalidate on CLI bumps). */
export const SANDBOX_CREDENTIALS_FILE = `${SANDBOX_HOME}/.claude/.credentials.json`
/** Onboarding state file — sits in CLAUDE_CONFIG_DIR, so inside the volume. */
export const SANDBOX_CLAUDE_JSON = `${SANDBOX_CONFIG_DIR}/.claude.json`
/**
 * Name the embedded deck-plugin (roadmap-card skill + roadmap-scribe agent,
 * back-channel/deck-control/demo-browser MCP bridges — desktop/deck-plugin)
 * lands under inside a sandboxed container. Re-exports DECK_PLUGIN_DIRNAME
 * (session-command.ts) rather than repeating the literal: reviewer (card
 * a79c7696 volet 1 review) measured THREE unpinned occurrences of
 * 'deck-plugin' -- this constant, the ProjectionEntry.name that drives
 * clean/chown in sandbox-service.ts, and index.ts's getDeckPluginDir host
 * basename. All three now derive from the one constant.
 */
export const SANDBOX_DECK_PLUGIN_NAME = DECK_PLUGIN_DIRNAME
/**
 * Where SANDBOX_DECK_PLUGIN_NAME lands inside a sandboxed container. Nested
 * under SANDBOX_CONFIG_DIR (not a sibling of it) on purpose: it reuses the
 * same clean/chown plumbing as the operator's projected config
 * (buildProjectionCleanArgs/ChownArgs are scoped to SANDBOX_CONFIG_DIR), it
 * is not a mount, and card a79c7696 volet 1's own "always" rule (project it
 * regardless of the operator's config-projection opt-out) is what
 * projectDeckPlugin() in sandbox-service.ts enforces.
 */
export const SANDBOX_DECK_PLUGIN_DIR = `${SANDBOX_CONFIG_DIR}/${SANDBOX_DECK_PLUGIN_NAME}`
// Re-exported so main-side consumers keep one import; the renderer reads it
// from @shared/types (this module is main-only). Relative import: this file
// must stay loadable by bun tests, which do not resolve the @shared alias.
export { SANDBOX_AUTH_PTY_ID, SANDBOX_BUILD_PTY_ID } from '../shared/types'
/** Dev-server ports published (127.0.0.1 only) when none are configured. */
export const DEFAULT_SANDBOX_PORTS = [3000, 5173, 8080]

const NAME_PREFIX = 'kory-sbx-'
const NAME_RE = /^kory-sbx-[0-9a-f]{12}$/

/**
 * Canonical slash form of an ABSOLUTE path (the Deck only ever hands absolute
 * dirs here): backslashes → `/`, duplicate and trailing separators collapsed.
 * Deliberately NOT node's resolve(): that would inject the HOST platform's
 * cwd/sep semantics and break the win32 mapping when computed elsewhere.
 */
function canonPath(p: string): string {
  const c = p.replace(/\\/g, '/').replace(/\/{2,}/g, '/').replace(/\/+$/, '')
  return c || '/'
}

/**
 * Normalize a project dir so the SAME project always hashes to the SAME
 * container regardless of trailing separators or Windows drive-letter casing.
 */
export function normalizeProjectDir(dir: string, plat: NodeJS.Platform = platform()): string {
  const c = canonPath(dir)
  return plat === 'win32' ? c.toLowerCase() : c
}

/** Deterministic per-project container name: kory-sbx-<sha256(projectDir)[0..12]>. */
export function containerNameFor(projectDir: string, plat: NodeJS.Platform = platform()): string {
  const hash = createHash('sha256').update(normalizeProjectDir(projectDir, plat)).digest('hex')
  return NAME_PREFIX + hash.slice(0, 12)
}

/** Only strings of the exact generated shape may reach the engine CLI. */
export function isSandboxContainerName(name: unknown): name is string {
  return typeof name === 'string' && NAME_RE.test(name)
}

/**
 * Map a host path to its container equivalent, or **null** when it is not
 * inside the mounted tree (worktrees are: `<project>/.worktrees/x` stays under
 * the mount by construction).
 *
 * null rather than a `/work` fallback ON PURPOSE: falling back means running
 * the agent in a DIFFERENT directory than the operator asked for, silently.
 * That happened for real — a symlinked project prefix (macOS `/var`) made
 * worktree paths canonical while the mount source was not, so every worktree
 * session landed in the project root. The caller now refuses the spawn with a
 * trace instead (session-service marks the tile exited).
 */
export function mapHostPathToContainer(
  hostPath: string,
  projectDir: string,
  plat: NodeJS.Platform = platform()
): string | null {
  const rootKept = canonPath(projectDir)
  const targetKept = canonPath(hostPath)
  const fold = (p: string): string => (plat === 'win32' ? p.toLowerCase() : p)
  const root = fold(rootKept)
  const target = fold(targetKept)
  if (target === root) return SANDBOX_WORK_DIR
  if (!target.startsWith(root + '/')) return null
  // Tail from the case-KEPT form so container paths keep their casing.
  return SANDBOX_WORK_DIR + targetKept.slice(rootKept.length)
}

/** POSIX single-quote escaping for values embedded in the launch script. */
export function shQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

/**
 * Rewrites the --plugin-dir flag in an already-composed command line to the
 * container path, since the host path it was built with is invisible inside the
 * sandbox and the plugin would fail to load silently.
 * A single fixed replacement is correct: there is exactly one deck-plugin per
 * app, always projected to the same container path. No-op when the flag is
 * absent.
 */
export function rewritePluginDirForContainer(command: string): string {
  return command.replace(/--plugin-dir "[^"]*"/, `--plugin-dir "${SANDBOX_DECK_PLUGIN_DIR}"`)
}

/** Rewrite a host-loopback URL so the container reaches the HOST's loopback. */
export function rewriteLoopbackForContainer(url: string): string {
  return url.replace(/\/\/(127\.0\.0\.1|localhost|\[::1\])(?=[:/]|$)/, '//host.docker.internal')
}

export interface SandboxCreateSpec {
  name: string
  image: string
  /** Host project dir — the kory.project label (identity, not the mount). */
  projectDir: string
  /**
   * Host dir actually bind-mounted at /work: the project itself in `mount`
   * mode, the ephemeral clone in `copy` mode (M3). Defaults to projectDir.
   */
  workSource?: string
  /** Host dir holding the generated launch scripts (bind-mounted at /kory-run). */
  runDirHost: string
  /**
   * Deck-owned peers dir, not the host ~/.claude/peers: mounting the real one
   * read-write would let a sandboxed agent rewrite another, non-sandboxed
   * tile's back-channel file and have the Deck resume it on the host — a
   * sandbox escape.
   */
  peersDirHost?: string
  /** Dev-server ports published as 127.0.0.1:p:p (webview reaches them as localhost). */
  ports: number[]
  /**
   * Mount-mode sub-policy (card 6e3863ef): nested `:ro` binds computed by
   * `planProtectedBinds` (sandbox-protect.ts), which is the only place that
   * touches disk in this family. Absent/`'not-applicable'` emits nothing.
   */
  protection?: ProtectionPlan
}

/**
 * Renders a `ProtectionPlan` into `-v <host>:<container>:ro` pairs, sorted by
 * ascending containerPath length for deterministic, testable output. Pure —
 * no disk access, mirrors the rest of this file.
 */
function protectionArgs(plan: ProtectionPlan | undefined): string[] {
  if (!plan || plan.status !== 'applied') return []
  const sorted = [...plan.applied].sort((a, b) => a.containerPath.length - b.containerPath.length)
  return sorted.flatMap((b) => ['-v', `${b.hostPath}:${b.containerPath}:ro`])
}

/**
 * `docker/podman create` argument vector. The container idles on
 * `sleep infinity`; every session/action is an `exec` into it. `--add-host`
 * covers native-Linux engines where host.docker.internal is not built in
 * (Docker Desktop Win/mac resolves it natively and ignores the extra entry).
 */
export function buildCreateArgs(spec: SandboxCreateSpec): string[] {
  const ports = [...new Set(spec.ports.filter((p) => Number.isInteger(p) && p > 0 && p < 65536))]
  return [
    'create',
    '--name',
    spec.name,
    '--label',
    'kory.sandbox=1',
    '--label',
    `kory.project=${spec.projectDir}`,
    '--add-host',
    'host.docker.internal:host-gateway',
    '-v',
    `${spec.workSource || spec.projectDir}:${SANDBOX_WORK_DIR}`,
    ...protectionArgs(spec.protection),
    '-v',
    `${SANDBOX_AUTH_VOLUME}:${SANDBOX_HOME}/.claude`,
    '-v',
    `${spec.runDirHost}:${SANDBOX_RUN_DIR}`,
    ...(spec.peersDirHost ? ['-v', `${spec.peersDirHost}:${SANDBOX_HOME}/.claude/peers`] : []),
    ...ports.flatMap((p) => ['-p', `127.0.0.1:${p}:${p}`]),
    spec.image,
    'sleep',
    'infinity'
  ]
}

export interface SandboxLaunchScriptSpec {
  /** Full session command line (claude --session-id … — already composed). */
  command: string
  /** Container-side cwd (a /work/… path from mapHostPathToContainer). */
  cwd: string
  /**
   * Env exported at the top of the script. The caller has already translated
   * host-only values (FORCE_GROUP file→inline, loopback URLs→host.docker.internal)
   * via sandboxifyEnv().
   */
  env: Record<string, string>
}

/**
 * The per-session launch script written to the run dir. A script — not `-e`
 * flags or an inline `bash -lc '…'` — because the outer command already
 * crosses `powershell -Command` on Windows (shell-command.ts) and a second
 * quoting layer over an arbitrary session command line is exactly the kind of
 * string-gluing the SBX plan forbids. `-l` keeps the image user's login PATH
 * (bun, claude in ~/.local/bin).
 */
export function buildLaunchScript(spec: SandboxLaunchScriptSpec): string {
  const lines = ['#!/bin/bash -l']
  for (const [key, value] of Object.entries(spec.env)) {
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue // never script-inject via a key
    lines.push(`export ${key}=${shQuote(value)}`)
  }
  lines.push(`cd ${shQuote(spec.cwd)} || exit 1`)
  lines.push(`exec ${spec.command}`)
  return lines.join('\n') + '\n'
}

/**
 * Translate the host session env for container use:
 *  - the chmod-600 FORCE_GROUP *file* transport (scope.ts) becomes the inline
 *    value (the host path does not exist container-side) — `readSecretFile`
 *    is injected so this stays pure;
 *  - loopback URLs (design endpoint) are rewritten to host.docker.internal;
 *  - CLAUDE_CONFIG_DIR is FORCED onto the shared volume (SANDBOX_CONFIG_DIR);
 *  - everything else passes through untouched.
 */
export function sandboxifyEnv(
  env: Record<string, string>,
  readSecretFile: (path: string) => string | null
): Record<string, string> {
  const out: Record<string, string> = {}
  for (const [key, value] of Object.entries(env)) {
    if (key === 'CLAUDE_PEERS_FORCE_GROUP_FILE') {
      if (value) {
        const secret = readSecretFile(value)
        if (secret !== null) out.CLAUDE_PEERS_FORCE_GROUP = secret
      }
      continue
    }
    if (key === 'CLAUDE_PEERS_FORCE_GROUP' && !value && env.CLAUDE_PEERS_FORCE_GROUP_FILE) {
      continue // superseded by the file translation above
    }
    if (key === 'CLAUDE_DECK_DESIGN_URL' && value) {
      out[key] = rewriteLoopbackForContainer(value)
      continue
    }
    out[key] = value
  }
  // Force the CLI's config root onto the shared volume for every session (see
  // SANDBOX_CONFIG_DIR): without it the onboarding state stays in the
  // container's own $HOME and the agent asks to sign in again although the
  // credentials are right there. Set LAST so a stray host value cannot win --
  // the host's own CLAUDE_CONFIG_DIR is a Windows path, meaningless here.
  out.CLAUDE_CONFIG_DIR = SANDBOX_CONFIG_DIR
  return out
}

/** Container-side path of a launch script written to the host run dir. */
export function scriptContainerPath(sessionId: string): string {
  return `${SANDBOX_RUN_DIR}/cmd-${sessionId}.sh`
}

/** Host-side file name of the same script (joined onto the run dir by the caller). */
export function scriptFileName(sessionId: string): string {
  return `cmd-${sessionId}.sh`
}

/** The PTY command that runs a sandboxed session: exec into the idling container. */
export function buildExecCommand(engine: SandboxEngine, name: string, sessionId: string): string {
  return `${engine} exec -it ${name} bash ${scriptContainerPath(sessionId)}`
}

/**
 * The credentials volume is app-wide, so every operation on it runs in a
 * throwaway container mounting nothing else — no /work, no run dir, no peers
 * dir, no published ports — the smallest possible mount set.
 */
function authVolumeMount(): string[] {
  return ['-v', `${SANDBOX_AUTH_VOLUME}:${SANDBOX_HOME}/.claude`, '-e', SANDBOX_CONFIG_DIR_ENV]
}

/**
 * The auth terminal command (SBX3): plain `claude` in a throwaway container —
 * the CLI detects the missing login and walks the operator through the OAuth
 * flow. The Deck polls the credentials file and kills this PTY on success.
 * `--rm` so an abandoned login leaves nothing behind.
 */
export function buildAuthCommand(engine: SandboxEngine, image: string): string {
  return `${engine} run --rm -it ${authVolumeMount().join(' ')} ${image} bash -lc claude`
}

/**
 * Checks both the credentials file and hasCompletedOnboarding in .claude.json:
 * the CLI writes credentials as soon as OAuth succeeds but keeps onboarding
 * open, and the login dialog kills the login PTY the instant a credentials-only
 * check would pass.
 * On a missing .claude.json a bare grep -q exits 2; the if/else collapses every
 * miss to exit 1 so probeAuth reads it as a plain not-signed-in rather than
 * engine trouble.
 */
export function buildAuthProbeArgs(image: string): string[] {
  return [
    'run',
    '--rm',
    ...authVolumeMount(),
    image,
    'sh',
    '-c',
    `if test -s ${SANDBOX_CREDENTIALS_FILE} && grep -qs hasCompletedOnboarding ${SANDBOX_CLAUDE_JSON}; then exit 0; else exit 1; fi`
  ]
}

/** Arg vector wiping the credentials file ("disconnect", guarded upstream). */
export function buildAuthPurgeArgs(image: string): string[] {
  return ['run', '--rm', ...authVolumeMount(), image, 'rm', '-f', SANDBOX_CREDENTIALS_FILE]
}

/**
 * Container-side transcript dir for a host cwd (M2 resume): Claude writes
 * `~/.claude/projects/<encoded cwd>/<id>.jsonl`, and inside the sandbox the
 * cwd is the CONTAINER path — so the encoding must run on the mapped path,
 * not the host one. `~/.claude` is the auth volume, so these transcripts
 * survive a container rebuild.
 */
export function containerTranscriptDir(
  cwdHost: string,
  projectDir: string,
  plat: NodeJS.Platform = platform()
): string | null {
  const containerCwd = mapHostPathToContainer(cwdHost, projectDir, plat)
  // Outside the mount there is no container-side transcript dir to look in —
  // null so the caller reports "unknown", never an empty (= "no transcript")
  // answer that would silently downgrade a resume to a fresh session.
  if (containerCwd === null) return null
  return `${SANDBOX_HOME}/.claude/projects/${encodeProjectDir(containerCwd)}`
}

/**
 * Arg vector listing a transcript dir as `<name>\t<mtime seconds>` rows.
 * GNU find (debian base image); a missing dir exits non-zero → empty list.
 */
export function buildTranscriptListArgs(name: string, dir: string): string[] {
  return ['exec', name, 'find', dir, '-maxdepth', '1', '-name', '*.jsonl', '-printf', '%f\\t%T@\\n']
}

/** Parse `buildTranscriptListArgs` stdout into transcript entries. */
export function parseTranscriptList(stdout: string): { id: string; mtimeMs: number }[] {
  const out: { id: string; mtimeMs: number }[] = []
  for (const line of stdout.split('\n')) {
    const [file, stamp] = line.split('\t')
    if (!file || !file.endsWith('.jsonl')) continue
    const seconds = Number.parseFloat(stamp ?? '')
    out.push({
      id: file.slice(0, -'.jsonl'.length),
      mtimeMs: Number.isFinite(seconds) ? seconds * 1000 : 0
    })
  }
  return out
}

/**
 * `docker cp -L <hostPath> <container>:<containerPath>` (config projection, M2).
 *
 * `-L` (follow the SOURCE link) is load-bearing, not tidiness: many operators
 * keep `~/.claude/CLAUDE.md`, `agents`, `skills` and `settings.json` as
 * symlinks into a versioned config repo. Without `-L`, `docker cp` copies the
 * LINK, which lands in the container pointing at a host path that does not
 * exist there -- so the operator's global config was silently absent from every
 * sandboxed agent while the Docker view happily reported it as projected.
 * Following the link is also the safer of the two: what crosses is a plain
 * file, never a pointer the container could resolve somewhere unexpected.
 */
export function buildCopyIntoArgs(name: string, hostPath: string, containerPath: string): string[] {
  return ['cp', '-L', hostPath, `${name}:${containerPath}`]
}

/**
 * docker cp -L overwrites a destination file but refuses to replace a
 * destination directory symlink with a real directory, so stale projected
 * entries are deleted before the copy to make it authoritative.
 * Only entries about to be re-copied are purged, never the whole allow-list, so
 * removing a host entry never deletes the container's last copy without a
 * replacement.
 */
export function buildProjectionCleanArgs(name: string, entryNames: string[]): string[] {
  // Entry names come from PROJECTED_ENTRIES via planProjection, but re-check
  // the shape anyway: a path separator (or a bare `.`/`..`, which the charset
  // alone would let through as `rm -rf ~/.claude/..`) would let a future
  // refactor reach outside ~/.claude (hostile input #4 — validate at the
  // boundary).
  //
  // `--user root`: `docker cp` writes the projected trees as ROOT, and the
  // container's default user (kory) may unlink the top-level entries (it owns
  // ~/.claude) but nothing INSIDE a root-owned dir — the first run as kory
  // sprayed hundreds of "rm: Permission denied" over plugins/.
  const safe = projectionSafeNames(entryNames)
  return ['exec', '--user', 'root', name, 'rm', '-rf', ...safe.map((n) => `${SANDBOX_CONFIG_DIR}/${n}`)]
}

/**
 * Post-projection ownership fix: `docker cp` lands the trees as root, and the
 * CLI (running as kory) then cannot WRITE its own copy — concretely
 * `plugins/installed_plugins.json` was read-only for the very process meant
 * to maintain it. The copy is the agent's to wreck (it dies with the
 * container), so kory owning it is the design, not a concession.
 */
export function buildProjectionChownArgs(name: string, entryNames: string[]): string[] {
  const safe = projectionSafeNames(entryNames)
  return [
    'exec',
    '--user',
    'root',
    name,
    'chown',
    '-R',
    `${SANDBOX_USER}:${SANDBOX_USER}`,
    ...safe.map((n) => `${SANDBOX_CONFIG_DIR}/${n}`)
  ]
}

function projectionSafeNames(entryNames: string[]): string[] {
  return entryNames.filter((n) => /^[A-Za-z0-9._-]+$/.test(n) && !/^\.+$/.test(n))
}

/** `docker build -t <image> <contextDir>` — the PTY command of the image build. */
export function buildImageBuildCommand(
  engine: SandboxEngine,
  image: string,
  contextDir: string
): string {
  return `${engine} build -t ${shQuote(image)} ${shQuote(contextDir)}`
}

/** Arg vector testing that the image exists locally. */
export function buildImageProbeArgs(image: string): string[] {
  return ['image', 'inspect', '--format', '{{.Created}}', image]
}

/**
 * Arg vector deleting the image locally. Deliberately NOT forced: the engine
 * refuses while any container was created from it, even a stopped one, and that
 * refusal is the honest answer to surface -- `-f` would orphan those containers
 * behind an untagged image id. The credentials volume is a separate object and
 * is never touched by this.
 */
export function buildImageRemoveArgs(image: string): string[] {
  return ['image', 'rm', image]
}

/**
 * Arg vector probing the broker bridge FROM INSIDE the container: the only
 * honest test of `host.docker.internal` reachability (it resolves natively on
 * Docker Desktop, needs --add-host + a non-loopback broker bind elsewhere).
 */
export function buildBrokerProbeArgs(name: string, brokerUrl: string): string[] {
  return ['exec', name, 'curl', '-sf', '-m', '4', '-o', '/dev/null', `${brokerUrl}/health`]
}

/**
 * Supervisor-driven exec (M2 `deck_sandbox_exec`): the agent's command line is
 * ONE argv element handed to the container's bash — it never touches a HOST
 * shell (hostile input #4). `-lc` gives it the image user's login PATH.
 */
export function buildSupervisorExecArgs(name: string, command: string): string[] {
  return ['exec', '-w', SANDBOX_WORK_DIR, name, 'bash', '-lc', command]
}
