package io.koryphaios.shell

// The bridge `platform.ts` calls (PLAN N5).
//
// Copy to android/app/src/main/java/io/koryphaios/shell/ after `cap add android`.
//
// Four methods, matching the `KoryphaiosShell` interface declared in
// `../src/platform.ts`. Each one is a capability a WebView cannot have; every
// one of them degrades to a documented no-op when the plugin is absent, which
// is what keeps the app runnable in a plain browser for development.

import android.content.Intent
import android.net.Uri
import android.os.Build
import android.os.PowerManager
import android.provider.Settings
import com.getcapacitor.JSObject
import com.getcapacitor.Plugin
import com.getcapacitor.PluginCall
import com.getcapacitor.PluginMethod
import com.getcapacitor.annotation.CapacitorPlugin

@CapacitorPlugin(name = "KoryphaiosShell")
class KoryphaiosShellPlugin : Plugin() {

    @PluginMethod
    fun startApprovalService(call: PluginCall) {
        val server = call.getString("server").orEmpty()
        val topic = call.getString("topic").orEmpty()
        val token = call.getString("token").orEmpty()
        if (server.isEmpty() || topic.isEmpty()) {
            call.reject("server and topic are required")
            return
        }
        (activity as? MainActivity)?.ensureNotificationPermission()
        requestBatteryExemption()
        ApprovalService.start(context, server, topic, token)
        call.resolve()
    }

    @PluginMethod
    fun stopApprovalService(call: PluginCall) {
        ApprovalService.stop(context)
        call.resolve()
    }

    /**
     * Open a paired Deck with its certificate pinned.
     *
     * `seedScript` is generated by `companionResumeScript` (tested TypeScript,
     * so the escaping is not improvised here) and runs BEFORE the page's own
     * script, which is what lets a known host resume without a fresh QR.
     */
    @PluginMethod
    fun openHost(call: PluginCall) {
        val url = call.getString("url").orEmpty()
        val fingerprint = call.getString("fingerprint").orEmpty()
        val seedScript = call.getString("seedScript").orEmpty()
        if (!url.startsWith("https://")) {
            call.reject("only https hosts can be opened")
            return
        }
        activity.runOnUiThread {
            CompanionWebView.open(activity, url, fingerprint, seedScript)
        }
        call.resolve()
    }

    @PluginMethod
    fun deviceName(call: PluginCall) {
        // MODEL rather than a user-set device name: it needs no permission and
        // it is only ever a label in the Deck's paired-devices list.
        call.resolve(JSObject().put("name", "${Build.MANUFACTURER} ${Build.MODEL}".trim()))
    }

    /**
     * Ask to be exempted from battery optimisation.
     *
     * AOSP Doze is survivable with a foreground service; several OEM skins are
     * not, and kill beyond the documented rules (dontkillmyapp.com). This is a
     * request, not a guarantee — the operator can refuse, and the channel then
     * behaves like any other app on that phone.
     */
    private fun requestBatteryExemption() {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) return
        val power = context.getSystemService(PowerManager::class.java)
        if (power.isIgnoringBatteryOptimizations(context.packageName)) return
        try {
            activity.startActivity(
                Intent(
                    Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS,
                    Uri.parse("package:${context.packageName}")
                )
            )
        } catch (e: Exception) {
            // Some builds hide the intent; the service still runs, it is just
            // more killable. Traced rather than swallowed.
            android.util.Log.w("koryphaios", "battery exemption prompt unavailable", e)
        }
    }
}
